[PORT FROM R42S]AMS: Two REMOVE_PROVIDER messages caused by race condition.
BZ: 73612

Fix a bug in unstable ContentProvider.
IllegalStateException: ref counts can't go to zero here: stable=0 unstable=0
IllegalStateException: unstable count < 0: -1

There is a race between main thread and background database thread. Main thread
is responsible for handling the REMOVE_PROVIDER message. Database thread starts
insert or query request again and again. acquireProvider in db thread will often
snatch provider from the jaws of death, sometime it fails to remove REMOVE_PROVIDER
which is already fired out from MessageQueue. But completeRemoveProvider in main
thread gets suspended when trying to execute the critical section. If db thread
released the provider before main thread resumes the execution, then two
REMOVE_PROVIDER messages will be executed.

Change-Id: Ib1020cf46ac390dbc4185524eb84b3a92549b0d4
Orig-Change-Id: I427330ab52cb4199dcb7614416c3e6e379f1611f
Signed-off-by: Guobin Zhang <guobin.zhang@intel.com>
Reviewed-on: http://android.intel.com:8080/116690
Reviewed-by: Wang, LiangX <liangx.wang@intel.com>
Reviewed-by: Yao, Yong <yong.yao@intel.com>
Tested-by: Chen, HuaqiangX <huaqiangx.chen@intel.com>
Reviewed-by: buildbot <buildbot@intel.com>
Tested-by: buildbot <buildbot@intel.com>